### ISSUE TITLE
只放代码，不考虑放题解吗

### ISSUE THREAD

**Issue by loheagn** [Great-designer/BUAA-OJ-Project#1]
一个建议，每个文件改成md文档，文档内首先可以有该题目的链接以及基本描述，然后根据题目的难易程度写一写题解，最后AC代码可以嵌入到md文档中。

**Comment by Great-designer** [comment]
我觉得比较特殊的难题可以考虑考虑，写写题解。短篇的实在没必要。
其实绝大多数题目的题解没什么必要。题解需要面向读者，将思路写成浅显易懂的东西，有的时候会很长。然而上千道题不可能都这么做。况且能到达GitHub的读者，本身也有一定的代码基础，大多数代码一定可以看懂。
所以我对代码本身格式要求很高，题解反而没什么要求。若是来稿中有题解，很好，没有也无所谓。只要能AC就行。
总之欢迎来投稿呦~直接放上去即可呢~

发送自 Windows 10 版邮件应用

发件人: loheagn
发送时间: 2020年4月7日 18:49
收件人: Great-designer/BUAA-OJ-Project
抄送: Subscribed
主题: [Great-designer/BUAA-OJ-Project] 只放代码，不考虑放题解吗 (#1)

一个建议，每个文件改成md文档，文档内首先可以有该题目的链接以及基本描述，然后根据题目的难易程度写一写题解，最后AC代码可以嵌入到md文档中。
